"""Build .ipynb files from compact python-cell sources.

Usage: python notebooks/build_notebooks.py
Reads notebooks/nb_sources/nbXX_*.py files where cells are separated by
"# %% [markdown]\n# ..." and "# %%\n<code>" markers (VS Code / jupytext style).
"""
from __future__ import annotations

import sys
from pathlib import Path

import nbformat as nbf

HERE = Path(__file__).parent
SRC_DIR = HERE / "nb_sources"


def parse_cells(text: str):
    cells = []
    kind = None
    buf: list[str] = []
    for line in text.splitlines():
        if line.startswith("# %% [markdown]"):
            if kind:
                cells.append((kind, "\n".join(buf).rstrip()))
            kind, buf = "markdown", []
        elif line.startswith("# %%"):
            if kind:
                cells.append((kind, "\n".join(buf).rstrip()))
            kind, buf = "code", []
        else:
            if kind is None:
                continue
            buf.append(line)
    if kind:
        cells.append((kind, "\n".join(buf).rstrip()))
    return cells


def build_one(src: Path) -> Path:
    nb = nbf.v4.new_notebook()
    md_header = nbf.v4.new_markdown_cell(
        f"# {src.stem.replace('_', ' ')}\n\nLunarAI — SIH 26166 notebook. Generated by build_notebooks.py.")
    nb.cells = [md_header]
    for kind, body in parse_cells(src.read_text(encoding="utf-8")):
        if kind == "markdown":
            # strip leading "# " used for markdown comments
            lines = [l[2:] if l.startswith("# ") else l for l in body.splitlines()]
            nb.cells.append(nbf.v4.new_markdown_cell("\n".join(lines)))
        else:
            nb.cells.append(nbf.v4.new_code_cell(body))
    out = HERE / f"{src.stem}.ipynb"
    nbf.write(nb, str(out))
    return out


def main() -> int:
    if not SRC_DIR.exists():
        print("no nb_sources dir")
        return 1
    outs = []
    for src in sorted(SRC_DIR.glob("nb*.py")):
        out = build_one(src)
        outs.append(out.name)
        print(f"built {out.name}")
    print(f"total: {len(outs)} notebooks")
    return 0


if __name__ == "__main__":
    sys.exit(main())
